name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        config: [Mac]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SFML
      run: brew install sfml

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
